services:
  postgres:
    image: postgres:16-alpine
    container_name: booking-payments-db
    environment:
      POSTGRES_DB: booking_payments
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: